

name: Build and apply

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# defaults:
#   run:
#     shell: bash
#     # Define the working directory for all run steps in the workflow
#     working-directory: ./web

jobs:

  deploy_on_aws:
    environment: test
    name: 'Deploy to aws'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
 
    - name: Build  
      run: docker build . --file Dockerfile --tag tmp-tf-image 
