

name: Build and apply

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# defaults:
#   run:
#     shell: bash
#     # Define the working directory for all run steps in the workflow
#     working-directory: ./web

jobs:

  deploy_on_aws:
    environment: test
    name: 'Deploy to aws'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
      
#     - name: Build  
#       run: docker build . --file Dockerfile --tag tmp-tf-image 
      
    - name: terrafom run 
      run: docker run -v $(pwd):/app -w /app -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                                             -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                                             -e AWS_REGION="ap-south-1" \
                                             --entrypoint sh hashicorp/terraform:1.4 \ 
                                             -c "pwd; ls -al; terraform -v ; terraform init; terraform fmt -check; terraform plan -input=false -var-file='test.tfvars'; terraform apply -auto-approve -input=false -var-file='test.tfvars' "
